[package]
name = "guessing-game"
version = "0.1.0"
edition = "2021"
authors = ["Pratik Sharma sharma.pratik2016@gmail.com"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
